- hosts: localhost
  connection: local

  tasks:
  - name: Create & Start Container
    docker_container:
      name: myhello
      image: "relaxmanitstime:{{ lookup('env','BUILD_NUMBER') }}"
      state: started
      ports:
      - "80:8080"
